# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='matriculas',
            field=models.ManyToManyField(to='usuario.Aluno'),
        ),
        migrations.AddField(
            model_name='turma',
            name='professores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Professor'),
        ),
        migrations.AddField(
            model_name='periodo',
            name='disciplinas',
            field=models.ManyToManyField(to='curriculo.Disciplina'),
        ),
        migrations.AddField(
            model_name='periodo',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.GradeCurricular'),
        ),
        migrations.AddField(
            model_name='gradecurricular',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.Curso'),
        ),
        migrations.AddField(
            model_name='disciplinaofertada',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.Disciplina'),
        ),
    ]
